### ISSUE TITLE
Error during installation through Cargo

### ISSUE THREAD

**Issue by wksinha** [XAMPPRocky/tokei#1011]
Upon running the following installation command for Cargo (as mentioned in the README.md):
cargo install --git https://github.com/XAMPPRocky/tokei.git tokei
the process terminates with error (details below).

Environment:
Manjaro/Arch Linux
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
rustc 1.70.0 (90c541806 2023-05-31)

Error message:
![Tokei-Installation-Error-Message](https://github.com/XAMPPRocky/tokei/assets/72341218/9810650c-6174-4966-b8e6-73f138bec813)

Installation through pacman works fine.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Since CI seems to be compiling fine, I wonder if it's a patch in the colorise dependency accidentally creating a breaking change.

**Comment by wksinha** [comment]
Possibly so, either Colorize, or Cell could have changed. The fix from Cargo seems to work. I have tried it and installation works fine after those changes. Created a pull request for the fix: https://github.com/XAMPPRocky/tokei/pull/1012

**Comment by Embers-of-the-Fire** [comment]
Sorry for that, I've forgotten that change in api. I'll yank 0.5.1 and republish it as a breaking version.

**Comment by wksinha** [comment]
Fix applied upstream, installation with Cargo works fine now. Closing issue.
