### ISSUE TITLE
All repositories have 0 lines of code

### ISSUE THREAD

**Issue by IlyaLisov** [XAMPPRocky/tokei#1069]
I see that every repository has 0 lines of code, even this one too

**Comment by ricardocardoso-dev** [comment]
Same here. Any predictions for fixing this?

**Comment by ToneXum** [comment]
They dont even render on my side.
![image](https://github.com/XAMPPRocky/tokei/assets/119890709/ce296fe9-743d-4c5e-bb06-d384b144602a)
Http response is just: `Invalid upstream response (525)`
