### ISSUE TITLE
not a 時計 but 統計

### ISSUE THREAD

**Issue by TOGUCHI-Chiseki** [XAMPPRocky/tokei#1086]
About README.md...
I think tokei means 統計, not a 時計.
Is this correct?

統計: statistics
時計: clock

**Comment by XAMPPRocky** [comment]
Thank you for your issue! It's supposed to translate to clock, it's word play on the fact the original tool is called "cloc" but you say it like "clock"

**Comment by TOGUCHI-Chiseki** [comment]
Oh, thanks.
I understood completely.
