### ISSUE TITLE
Option to reorder or select the columns in the output

### ISSUE THREAD

**Issue by furkanusta** [XAMPPRocky/tokei#1181]
Hi, not sure how easy/hard would it be but I am normally using `cloc` and wanted to switch to `tokei`. 
However the column order is tripping me off since I am used to having `code` column at the end and most of the time I am only glancing at the bottom right corner of the output.

Would it be possible to reorder columns or select which ones are present so I can disable `comments` and `blanks` ?

Thanks

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You can customise the sorting with "--sort", which you can also set in a token.toml in your home directory to consistently sort it that way, but I don't think we're going to allow column sorting or hiding.

https://github.com/XAMPPRocky/tokei/blob/master/tokei.example.toml
