### ISSUE TITLE
Optionally formatting numbers with a thousands separator

### ISSUE THREAD

**Issue by BrainMaestro** [XAMPPRocky/tokei#256]
Would you be interested in including this functionality (hidden behind a flag of course). It's easier to read `49,341` than `49341`.

**Comment by Aaronepower** [comment]
Thank you for your issue! I'd be interested in this though I'm unsure what is the best way to work this with the percentage column you're currently working on.

**Comment by skorokithakis** [comment]
I would also love this feature, the numbers are a bit hard to read as they are now.

**Comment by HarrisonMc555** [comment]
Would you be interested in help with this? I'd be willing to look into this with a bit of pointing in the right direction.

**Comment by XAMPPRocky** [comment]
@HarrisonMc555 Hello, thank you for your interest in helping! Thinking on this issue more I would accept a PR that adds a `num-format` (or something similar) that accepts a value that maps to enum of how to present the numbers, then print the number based on the style.

**Bonus** if the option also somehow provides a way to show it with different separators, as `,` isn't universal. There's probably a way to do this based on locale information, but I would also accept just adding another variant.

I would start with making this a CLI option, so most of the code you'll need to look at is `src/cli.rs`, `src/main.rs`, and `src/cli_utils.rs`. Once that works it would be nice for this to be available in the configuration file (`src/config.rs`) as well.

I've put an example of the flag and enum below, but feel free to change as you see fit. If have any questions feel free to ask!

### Flag
```
-n --num-format
 Accepts:
 - plain (default if not present)
 - seperated
 - dotted
```

### Rust enum
```rust
enum NumberResultStyle {
   // 1234 (Default)
   Plain,
   // 1,234
   Seperated,
   // 1.234
   Dotted,
}
```

**Comment by HarrisonMc555** [comment]
Ok sounds great! I would vote for having the variants be `plain`, `commas`, and `dots` (`separated` vs. `dotted` seems inconsistent to me). How do you feel about that?

I'll also look into using locale information, but I'll probably just do these three variants first.

**Comment by HarrisonMc555** [comment]
Would you be willing to include the [`num_format`] crate? It kind of seems like a lot for a simple task, but it is explicitly designed for this task. It would give us both an explicit commas/dots separators and could (optionally) auto-detect the system locale.

[`num_format`]: https://crates.io/crates/num-format

**Comment by XAMPPRocky** [comment]
I think that crate would be totally fine to include with the system locale feature. tokei already depends on some of `num_format`'s dependencies anyway, so it's a pretty small addition relatively. The serde feature should also be fine for the same reason, but I didn't look into whether it's actually useful.
