### ISSUE TITLE
Semantic nested comments for clojure

### ISSUE THREAD

**Issue by kornysietsma** [XAMPPRocky/tokei#284]
I attempted to implement clojure comment blocks, but the current nested language parsing doesn't handle them as the `(comment` block is seen as ending at the first closing `)`:
```
(comment 
  (if (foo) bar)
  still a comment line
)
```

Some cases might be tricky to handle - clojure `(comment blah)` blocks are handled by a macro that is processed after `;` comments are removed, so this is valid:

```
(comment blah blah
   (nested stuff
    ; nested line comment ignored including )))s
  )
)
```

And clojure also has a comment reader macro `#_(` which is even more lenient:
```
#_( allows: invalid syntax! As long as parens match)
```

But 99% of cases would be handled if you could just specify that `(comment` and `#_(` ignore any nested parenthesis pairs.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Sorry for the late reply. I don't think it is in the scope of Tokei to count anything that would require a language specific parser. With being a general language code counter there is always going to be some amount of accuracy lost.
