### ISSUE TITLE
Asciinema recording will be archived soon

### ISSUE THREAD

**Issue by Darksonn** [XAMPPRocky/tokei#290]
I clicked the recording in the README to view it and saw the following message in the header of the page:

> This recording will be archived soon. More details: blog.asciinema.org/post/archival/

You should probably follow their instructions to ensure the recording isn't removed.

**Comment by Porkepix** [comment]
It have now been archived and therefore can't bee watched anymore.

**Comment by alexreg** [comment]
@Aaronepower I trust you're aware of this? :-)

**Comment by Aaronepower** [comment]
Thank you for this issue! Yes I am aware of this, and I just haven't had the time to create a gif to embed into the GitHub page. If someone has a high quality gif of tokei running in its own directory I would be happy to use that.

**Comment by LovecraftianHorror** [comment]
Are there several commands you would want demonstrated, or would a screenshot of `tokei`'s output also be sufficient?

**Comment by XAMPPRocky** [comment]
Sorry for not updating this, I have since made several attempts at a high quality gif to replace the original asciiema recording, however the problem is that the gif would be so large for the quality I would want. I'm going to close this issue and file a new one.
