### ISSUE TITLE
Anti-quote support

### ISSUE THREAD

**Issue by Apanatshka** [XAMPPRocky/tokei#295]
I'm adding a language to tokei, and I just realised that quotes in this language are bit funny... You can create strings like this:

```
$[The string starts here after the dollar and bracket, but you can add string variables with more brackets for antiquoting like so: [stringVar], and you can't use square brackets directly so you need to antiquote them like ["[]"], and this is a run-on sentence so I'm going to stop now]
```

The antiquoting (not sure if that's the right term) allows arbitrary expressions including comments in the middle of the string, so you can get extra comment lines in the middle too. 

Is this something that can be supported?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Sorry for the late reply, Currently tokei doesn't have a way to handle that, and I don't think I would add one as its not a common feature.
