### ISSUE TITLE
Get lines of code by folder

### ISSUE THREAD

**Issue by pankajmalhotra** [XAMPPRocky/tokei#300]
Is there a way we can lines of code folder level using tokei?
example:

I have a repository which has five folders, is there a way I can pass a flag which can give lines of code per folders ?

1. folder1 --> 100
2. folder2 --> 50

**Comment by Aaronepower** [comment]
@pankajmalhotra Hello, thank you for your issue! Is this problem not solved by `tokei folder1 && tokei folder2`?

**Comment by thebigmunch** [comment]
> @pankajmalhotra Hello, thank you for your issue! Is this problem not solved by `tokei folder1 && tokei folder2`?

That would get pretty tedious for more than a small number of directories. I think what they are looking for is a directory version of the ``-f, --files`` option. This would give a quick overview of a project, for example.

**Comment by Aaronepower** [comment]
@thebigmunch For larger number of directories I would suggest a simple script. I'm hesitant to add this feature as the actual behaviour is currently unclear, I've written down a list of concerns below. I feel they adequately show how implementing this feature in a external script is the easiest solution, as removes these worries and still provides what the user expects.

* What would one expect the output to be of projects with multiple nested directories? Right now tokei displays for `--files` the list of files with the total for the language, now with `—directories` tokei would have to total the directories, display the total for that directory, and repeat until it has reached back to the top level of the directory.
* How should this also work with files? Intuitively they should work together, but now the repeating totalling issue I mentioned previously is even worse with both of these flags enabled.
* How would the internals of tokei be structured to avoid any significant slowdown? Right now tokei doesn't store any information about directories when it traverses the filesystem. Tokei simply takes the file path and puts into the "bucket" of its respective language, how would the code handle remembering directories without a huge rewrite and slow down?
