### ISSUE TITLE
UTF error with pre-built v9.0

### ISSUE THREAD

**Issue by pombredanne** [XAMPPRocky/tokei#301]
Using the prebuilt `tokei` CLI v9.0 [tokei-v9.0.0-x86_64-unknown-linux-gnu.tar.gz](https://github.com/Aaronepower/tokei/releases/download/v9.0.0/tokei-v9.0.0-x86_64-unknown-linux-gnu.tar.gz) on Ubuntu 16.04 LTS on x86_64, I am getting this error when counting some code.
```
[2019-02-11T08:23:29Z ERROR tokei::utils::fs] stream did not contain valid UTF-8 reading test/gobject.rc.in
```
The attached [utf-test.zip](https://github.com/Aaronepower/tokei/files/2850234/utf-test.zip) contains the files that triggered this.

All these are test files from https://github.com/nexB/scancode-toolkit (I am considering bundling tokei in ScanCode). The common theme is that they contain non-ASCII chars. Also some contain broken comments (e.g. a C `/*` without a closing `*/`

All were eventually collected from code that's actually used and existing: I could not expect a failure based on file encoding as in some cases you cannot determine what the original is and certainly will get other things than UTF-8.

**Comment by pombredanne** [comment]
@udoprog I guess this may be fixed with #280 , is this correct? (nb: I am a Rust noob)

**Comment by ptupitsyn** [comment]
I get the same issue (using pre-built 9.1.1 https://github.com/XAMPPRocky/tokei/releases/download/v9.1.1/tokei-v9.1.1-x86_64-unknown-linux-gnu.tar.gz).

Example file: 
[de.inc.zip](https://github.com/XAMPPRocky/tokei/files/3132403/de.inc.zip)

**Comment by XAMPPRocky** [comment]
Thank you for the issue! I have fixed this error in the master branch and it will be available in the next release.
