### ISSUE TITLE
C# line count is broken if verbatim string with backslash is present

### ISSUE THREAD

**Issue by ptupitsyn** [XAMPPRocky/tokei#330]
**Describe the bug**
Count is broken when there is a line in C# file with verbatim string in it like this:
`private const string BasePath = @"a:\";`.

**To Reproduce**

1. Download file [SccTokeiFailure.zip](https://github.com/boyter/scc/files/3132587/SccTokeiFailure.zip)
2. Extract
3. `tokei`

**Actual behavior**
```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C#                      1           20           17            0            3
-------------------------------------------------------------------------------
 Total                   1           20           17            0            3
-------------------------------------------------------------------------------
```

**Expected behavior**
```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C#                      1           20           14            3            3
-------------------------------------------------------------------------------
 Total                   1           20           14            3            3
-------------------------------------------------------------------------------
```

**Tested on**

* Debian 9.7
* Windows 10

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes tokei has no concept of verbatim strings. Do you know of any more languages with verbatim strings? I know Rust has them. I'll try to add this for the next version of Tokei.

**Comment by ptupitsyn** [comment]
F# has them same way as C#. C++ has Raw Strings. Groovy has some form of that too AFAIK.

**Comment by rgl** [comment]
Python has them too, e.g. normally are used to write literal regular expression as-in `r'.+\.+'`.

**Comment by NickHackman** [comment]
@XAMPPRocky I'd be happy to look into this, if you don't mind :smile:

**Comment by XAMPPRocky** [comment]
@NickHackman You're more than welcome to, it's important to be aware that some languages have simple verbatim strings where it's essentially a different quote syntax, and there are languages like Rust that allow you to have a more complex syntax such as `r####"Hello World"####` where the preceding `#`'s must match the `#`'s at the end. This is pretty uncommon however and I would accept something that only handles them like a quote syntax and for Rust includes `r#` and `r##` as those are two most common levels.
