### ISSUE TITLE
FR: List of file paths to ignore

### ISSUE THREAD

**Issue by turbo** [XAMPPRocky/tokei#333]
I'm aware that tokei has an exclude option, but in my case, it's scanning hundreds of thousands of files. A lot of them have to be ignored on a single file basis (no pattern, not ignoring a directory). Since this will exceed the maximum command line length, I'd like to be able to give the exclude option a file with a list of paths to ignore.

In general, I'd like to supply configuration to tokei via a file instead of command line parameters, but that's not what this request is about (though it would be an elegant way to solve this - TOML or something).

**Comment by XAMPPRocky** [comment]
@turbo Tokei does respect any `.tokeignore` files in the starting directory, this file uses the same syntax as `gitignore`. You can see an example of this in the tokei repository itself.
