### ISSUE TITLE
Donate link broken?

### ISSUE THREAD

**Issue by cdeil** [XAMPPRocky/tokei#334]
The Donate button in the README links to https://liberapay.com/XAMPPRocky/donate

Looks like it's broken:

![Screenshot 2019-05-14 at 09 45 43](https://user-images.githubusercontent.com/852409/57680107-29e52600-762d-11e9-8b42-064baee5d31c.png)

Fix or remove?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've now removed that link.
