### ISSUE TITLE
It's so slow to show the badge of 'total lines' in Github project page

### ISSUE THREAD

**Issue by HaojunRen** [XAMPPRocky/tokei#345]
Just as title, any improvements? More time it's show failed

**Comment by HaojunRen** [comment]
These days it can't display any more

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've updated  the production version of `tokei_rs` and put the domain behind Cloudflare, so the badges should now appear quickly. For future issues I'd recommend filing them on the [`tokei_rs`](//github.com/XAMPPRocky/tokei_rs) repository.

**Comment by HaojunRen** [comment]
Thanks a lot! It works fine!
