### ISSUE TITLE
exclude option does not work recursively

### ISSUE THREAD

**Issue by dineshba** [XAMPPRocky/tokei#350]
Command Used: 
```sh
 tokei . -o json  --exclude **/*.yaml
```

Directory structure:
```
├── dir1
│   ├── level1.yaml
│   ├── dir2
│   │   ├── level2_2.yaml
│   │   ├── level2_1.yaml
```

Expected: Ignore all yaml files in all levels.

Actual: Only ignores top level.

This works if i use a `.tokeignore` file at the top level but the command does not.

**Comment by XAMPPRocky** [comment]
Hello thank you for your issue! I believe is your shell automatically expanding `**/*.yaml` into all the paths available at the top level. To make the tokei command behave properly you need to pass as a string using single quotes as then the shell should expand the glob pattern. e.g.

```
tokei . -o json  --exclude '**/*.yaml'
```

**Comment by dineshba** [comment]
It works. Thanks alot.
