### ISSUE TITLE
differences with cloc

### ISSUE THREAD

**Issue by dataf3l** [XAMPPRocky/tokei#352]
same folder, two different tools, no .gitignore in sight,
widly different results.
I just don't know who to believe anymore.
Does anybody have a guess as to why the tools show such different numbers?

Also, thank you *so much* for building this tool,
I'll try to study the source code and try to learn from it

````
localhost: b$ tokei .
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 CSS                    19        19015        15795          492         2728
 HTML                    6          272          244            9           19
 JavaScript             83        82692        57203        15436        10053
 Markdown                1           56           56            0            0
 Rakefile                6          147          117           16           14
 Ruby                  364        14759        11780         1247         1732
 Sass                   13        22238        20735          158         1345
 SVG                     4          600          598            2            0
 Plain Text              1            5            5            0            0
 YAML                   21          374          271           60           43
-------------------------------------------------------------------------------
 Total                 518       140158       106804        17420        15934
-------------------------------------------------------------------------------
localhost: b$ cloc .
     734 text files.
     727 unique files.
      46 files ignored.

github.com/AlDanial/cloc v 1.76  T=1.26 s (562.3 files/s, 120004.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      83          10053          16933          55706
Sass                            13           1345             50          20843
CSS                             19           2728            492          15795
Ruby                           370           1746           1263          11897
ERB                            197            289              0          11270
YAML                            19             40             51            265
HTML                             6             19             11            242
Markdown                         1             26              0             30
-------------------------------------------------------------------------------
SUM:                           708          16246          18800         116048
-------------------------------------------------------------------------------
localhost: b$
````

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You can read the [comparison document](//github.com/XAMPPRocky/tokei/blob/master/COMPARISON.md) which has a section on accuracy that you can look at. You can also read the [limitations of cloc's accuracy](https://github.com/AlDanial/cloc#limitations-), tokei has a lot of the same limitations except it can handle comments in most string syntaxes (There are some form of strings that require a language specific parser). Overall Tokei is generally more accurate due it's state machine design vs Cloc's regular expression design. Non language specific tools sacrifice perfect accuracy for supporting so many languages, and should not be viewed as definitive.

**Comment by dataf3l** [comment]
Does this mean in order to have a fast reliable counter, one will need to implement parsers for each and every language!? That sounds time consuming and not fun at all...

**Comment by XAMPPRocky** [comment]
If you wanted to have a perfectly accurate one, yes. Each language has a different formal grammar, and while a lot overlap, a lot don't in major ways. I should also note that for most people Tokei should be just as accurate as a language specific parser. It's only when you have extreme edge cases, or you have a language who's comments/strings require a language parser to even be understood as comments/strings will Tokei's accuracy diminish.

**Comment by dataf3l** [comment]
is there a way to validate this "for most people" statement, by doing some kind of statistical analysis?, do we need to write the thing so we can compare?

**Comment by XAMPPRocky** [comment]
You can look at the [accuracy section](https://github.com/XAMPPRocky/tokei/blob/master/COMPARISON.md#accuracy) of the comparison document which compares how each code counter handles a complex(for code counters) Rust file.
