### ISSUE TITLE
tokei.rs down

### ISSUE THREAD

**Issue by vncoelho** [XAMPPRocky/tokei#357]
https://tokei.rs looks to be down.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I am aware it is down, I'm currently performing maintenance on the server. I would expect a few more hours of downtime, as I'm performing a fresh install, and I haven't migrated it to docker yet.

**Comment by vncoelho** [comment]
Sure @XAMPPRocky, thanks for reporting.

It would be nice if the NGINX route was left open...ahueahuea
Anyway. Nice job you are all doing.

Thanks for the quick reply.

**Comment by XAMPPRocky** [comment]
Tokei.rs is now back in the future it would be helpful if you file issues about tokei.rs to [it's repo](https://github.com/XAMPPRocky/tokei_rs/).
