### ISSUE TITLE
Feature Request: COCOMO

### ISSUE THREAD

**Issue by BartMassey** [XAMPPRocky/tokei#359]
The COCOMO estimator in David A. Wheeler's 'SLOCCount' by David A. Wheeler implements software cost/effort estimation using some default parameters that are included in David A. Wheeler's 'SLOCCount' but are configurable as shown [here](https://dwheeler.com/sloccount/sloccount.html#cocomo). This has been a big win for the open source community, who can point to these very rough estimates to impress journalists and the like with the scale of what is being accomplished.

It would be great if `tokei` could do this too, especially since `tokei` counts a lot more languages than Rust and is only going to get better.

Even better would be to be able to count "logical lines" to feed to a COCOMO II model.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I however have no interest in including this feature in tokei. I don't how COCOMO is a win for the open source community when it is a cost evaluation model for corporations. I don't think people should be using lines of code as a estimate of complexity of a project, and I certainly don't think we should be using lines of code to assign an arbitrary value to people's work.

> Even better would be to be able to count "logical lines" to feed to a COCOMO II model.

There's no concept of logical lines in programming languages, what you usually have is "statements" or "expressions", and understanding how to parse a statement or expression requires a language specific parser, which to maintain or reach tokei's current language support would require ~180 language parsers.

If you're looking for a sloccount alternative with COCOMO, I'd suggest looking at [scc](https://github.com/boyter/scc)

**Comment by BartMassey** [comment]
Thanks for the clear answer! `scc` looks pretty nice, so thanks for this recommendation also.

> I don't [know] how COCOMO is a win for the open source community when it is a cost evaluation model for corporations. I don't think people should be using lines of code as a estimate of complexity of a project, and I certainly don't think we should be using lines of code to assign an arbitrary value to people's work.

I can't argue with this as a matter of engineering principle. That said, if you're somebody who has no idea how programming works, getting a rough order of magnitude guess as to build time and potential value can be really useful in understanding. COCOMO isn't great, but if it says 10 years and $10M it's unlikely that the right answer is 10 weeks and $10K; also vice-versa. You have to remember that even today many people making policy decisions that affect open source barely understand how programming works.

I totally understand your reasoning, and want to be clear that am not trying to talk you into anything. Thanks much for writing and sharing `tokei`.

**Comment by qtfkwk** [comment]
I know this is an old/closed request... but came across it today. If interested... I just wrote and published a quick implementation in Rust using tokei and clap for a CLI. Please see https://crates.io/crates/
