### ISSUE TITLE
Cargo.lock for v10.0.1 release is out of date

### ISSUE THREAD

**Issue by lilyball** [XAMPPRocky/tokei#360]
The `Cargo.lock` file in v10.0.1 is out of date, the `version` field for the `tokei` package entry is wrong.

I don't know what sort of release process you have, but it would be great to ensure a `cargo build` is done before tagging the release.

**Comment by lilyball** [comment]
In particular, this is a problem when trying to use a package manager that builds with `cargo build --frozen`, as the build fails due to this issue.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! There's now a new release (10.1.2) which doesn't have this issue.
