### ISSUE TITLE
JSON output format changed without notice

### ISSUE THREAD

**Issue by lilyball** [XAMPPRocky/tokei#361]
The JSON output format changed to wrap everything in a key called `inner`. This is pretty weird and wasn't in the changelog.

Ideally this would be reverted. If there's some need to separate the per-language listing from other info, then this `inner` key should instead be changed to something like `languages`. Either way, this also needs to go into the changelog, and the output format should be kept as stable as possible going forwards.

**Comment by XAMPPRocky** [comment]
@lilyball Thank you for your issue! However this change wasn't without notice as it came with a major semver version. I'd also like to point out that this change isn't recent. Looking at the git blame of `src/language/languages.rs` this struct has had the inner field for over three years.

I'm also not going to make any stability claims other than my best attempt at following semver. I am not paid for my work on tokei, so I do not have the resources to provide any kind of stability support.

**Comment by lilyball** [comment]
Version 7.0.2 did not serialize the `inner` struct to the `json` output. I'm not going to exhaustively binary-search your releases to figure out when that started showing up, but my "without notice" comment is the fact that the changelog makes no mention of the JSON output changing.
