### ISSUE TITLE
CONTRIBUTING.md does not mention format of top comment

### ISSUE THREAD

**Issue by JHaig343** [XAMPPRocky/tokei#365]
the part in particular:
```markdown
# Tests
A test file is required with language additions. The file should
contain every variant comments and quotes, as well as a comment
at the top of the file containing the manually verified lines,
code, comments, blanks e.g.
`// 39 lines 32 code 2 comments 5 blanks`. The comment should use
the syntax of the language you're testing. A good example of a
test file is [`tests/data/rust.rs`].
```
Currently for tests to successfully run, the top comment needs to have a specific format:
`X lines X code X comments X blanks`
Which to md file does not mention. I propose adding to the md file to specifically mention the required format of the top comment.

**Comment by JHaig343** [comment]
#63

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've updated the contributing information.
