### ISSUE TITLE
languages.json includes HolyC but the list of supported languages in the readme does not

### ISSUE THREAD

**Issue by DanteFalzone0** [XAMPPRocky/tokei#388]
My fault since I'm the one who submitted pr #385. Thought I should let y'all know; didn't want to open a whole new pr for something so minor.

**Comment by XAMPPRocky** [comment]
@DanteFalzone0 Thank you for your issue! All PRs large and small are welcome.

**Comment by DanteFalzone0** [comment]
Okay then
