### ISSUE TITLE
Feature request: ignore comment blocks at beginning of file

### ISSUE THREAD

**Issue by hmijail** [XAMPPRocky/tokei#391]
Typically one can find lengthy comment blocks with license text at the beginning of every file. This artificially inflates the number of comment lines in the project. Would it be possible to add an option to not count the comment lines in such blocks?

**Comment by hmijail** [comment]
(There is also the case of SPDX license identifiers, which also happen at the beginning of files but as a single-line comment. So ignoring such comments would also be useful)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However I'm not so sure I agree with the idea that these are not comments.`tokei` isn't designed to provide some semantic analysis for the comments, so adding this would require significant changes that I don't think are worth what this feature would provide.
