### ISSUE TITLE
Ignore tests?

### ISSUE THREAD

**Issue by dpc** [XAMPPRocky/tokei#396]
I wonder if it would be possible to ignore lines of code for tests.

In `cargo-crev` I'd like to display the LoC-based "weight" of the crate, but as things are right now, the crates that have a lot of test code, will appear heavier, even though that code is not being run in normal usage.

I guess I could resort to some form of pattern matching, but that's not perfect.

**Comment by XAMPPRocky** [comment]
Thank you for your issue!  I don't think needs to be implemented on the tokei's side at least initially. Determining what is and is not test code inside the source file isn't something that can be done in a general fashion as every language's testing structure is different in both semantics and syntax that it would require language specific parsing. If the user knows that a whole file is test code they can provide paths for tokei to exclude from counting.

**Comment by dpc** [comment]
The thing is - I'm using `tokei` to count any random projects, so I can't be sure where are all the tests. I did add ignore filters on `./tests/` and `./examples/` which is getting me like 90%  there.

I realize that it is not trivial so I just propose it as a idea for a future feature. In the similar way that `tokei` can tell comments from code, it could ... at least in the languages that do have a standard way to mark them (like Rust) ... tell tests and examples automatically too.

I fully understand if this never actually get implemented. :)

**Comment by XAMPPRocky** [comment]
Yes, to be clear what I'm saying is someone could write a program that figures out your project layout and knows what your `src` directory is, and you could use that program with tokei as a library, this wouldn't require tokei at all, since tokei is about detecting programming language source and the problem you want to solve is about common project filesystem patterns.

You can also add a `.tokeignore` to the directory of the project and tokei will respect those ignore rules.

**Comment by dpc** [comment]
@XAMPPRocky There's still `#[test]` inline, but that's a good point.

**Comment by XAMPPRocky** [comment]
Here's an example of such kind of a project that does use tokei for part of its statistics. https://github.com/o2sh/onefetch

**Comment by nviennot** [comment]
I've made a fork that accounts for Rust tests here: https://github.com/nviennot/tokei
