### ISSUE TITLE
Add `--include` next to `--exclude`

### ISSUE THREAD

**Issue by Bios-Marcel** [XAMPPRocky/tokei#400]
I was just trying to find out how much of my code was test-code. All my test files are following the pattern `xxx_test.go`. However, I can't say to only check the test files, but to skip the text files and then having to manually do the math. I think it'd be nice to have `--include` for such cases.

**Comment by XAMPPRocky** [comment]
@Bios-Marcel You are able to do this already, the paths you provide as arguments to tokei act the same an `--include` flag would. For example if you wanted to count every file with `_test.go` you could use `tokei *_test.go`. Also —exclude`'s behaviour is the same as a ignore file so if you provide ` tokei --exclude='!*_test.go'` that would include every go file with `*_test.go` like the first example.

**Comment by Bios-Marcel** [comment]
Oh I see. I missunderstood that :D

The help doesn't mention that it allows patterns, same goes for `--exclude`. Maybe the help text should be improved then.

**Comment by XAMPPRocky** [comment]
I don't have the time currently to fix this documentation. I would be happy to accept a PR in the mean time that makes it more clear. The syntax of a gitignore file can be read about here https://git-scm.com/docs/gitignore

**Comment by Bios-Marcel** [comment]
A gitignore file? I am not sure why that matters for this issue? :sweat_smile:

**Comment by XAMPPRocky** [comment]
@Bios-Marcel The syntax of `--exclude` pattern is the exact same as that of a gitignore file.

**Comment by Bios-Marcel** [comment]
Oh, I see. Thanks. I'll take a look tomorrow and make a PR :)

**Comment by XAMPPRocky** [comment]
@Bios-Marcel You might also want to know that you can have a [`.tokeignore`](https://github.com/XAMPPRocky/tokei/blob/master/.tokeignore) for always having tokei ignore files when run in that directory.
