### ISSUE TITLE
Prolog not recognized with extension pl

### ISSUE THREAD

**Issue by rrooij** [XAMPPRocky/tokei#407]
Prolog code with the extension `.pl` is not recognized. And unfortunately, perl also uses this extension. We need some way of distinguishing perl and prolog. When I tried to add the `pl` extension to prolog in the `languages.json` I got an unreachable block error on compilation.

Proof that the .pl is extension is used in the prolog community:

https://www.swi-prolog.org/pldoc/man?section=fileext

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Currently tokei does not have this functionality, I intend to add the ability to specific extension overrides to the `.tokeirc` file format shortly. In mean time I'm going to close this issue as a duplicate of #67
