### ISSUE TITLE
`tokei` shows incorrect values for python doc comments

### ISSUE THREAD

**Issue by LovecraftianHorror** [XAMPPRocky/tokei#413]
For a file like

```python
'''doc comment with single quotes'''
"""doc comment with double quotes"""
```

`tokei` counts the doc comments as code instead of comments. Showing

```text
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Python                  1            2            2            0            0
-------------------------------------------------------------------------------
 Total                   1            2            2            0            0
-------------------------------------------------------------------------------
```

when it should be considered only 2 lines of comments and nothing else.

**Comment by XAMPPRocky** [comment]
@LovecraftianHorror Thank you for your issue. This is not actually incorrect as triple quote strings are valid code in python. However you can add a `.tokeirc`/`tokeirc.toml` file to your project and `treat_doc_strings_as_comments = true` to it and tokei will count doc strings as comments always. Please refer to the [example `.tokeirc`](https://github.com/XAMPPRocky/tokei/blob/master/.tokeirc.example) for other options.
