### ISSUE TITLE
Tokei misses some shell files

### ISSUE THREAD

**Issue by kbd** [XAMPPRocky/tokei#431]
Tokei isn't counting files (with no extension) as shell whose shebang is `#!/bin/bash`. It's indeed not accounted for in [`get_filetype_from_shebang`](https://github.com/XAMPPRocky/tokei/blob/2c41fdb182b7ba1bcc7c9d1cfc0de569538e7f0d/src/language/language_type.hbs.rs#L458).

Fwiw, the best reference I know of for "find all shell [and other] files" is `ack`, [whose heuristic is](https://beyondgrep.com/documentation/):

Has extensions: .sh .bash .csh .tcsh .ksh .zsh .fish, or first line matches `/^#!.*\b(?:ba|t?c|k|z|fi)?sh\b/`.

**Comment by evitalis** [comment]
I ran into the same thing when I copied a shellscript to a `.default` or `.orig` to make some changes and compare line numbers. I at the moment do not feel good enough with Rust to take a shot at fixing this though.

**Comment by solanav** [comment]
I think I could do this. I believe I could either manually add the rest of the popular shells that are missing (tcsh, bash, ksh, zsh and fish) or use awk's regex to match all these shells and make get_filetype_from_shebang return "shell" when the regex matches.

**Comment by XAMPPRocky** [comment]
@solanav Thank you for your interest in adding this feature. Thinking on this more I think it would be beneficial to do it by adding an `shebang_paths` property to `languages.json`, that we can then add common full shebang paths to any language. Then it's easier to maintain and add more in the future.

```json
"shebang_paths": ["#!/bin/sh"]
```

**Comment by solanav** [comment]
Sounds good to me, I'm going to get more familiarized with the codebase and try to implement this.

**Comment by XAMPPRocky** [comment]
@solanav So this part of tokei is quite unique compared to other codebases. Tokei uses handlebars at build time to generate Rust code for every language. You should only need to change `src/language/language_type.hbs.rs` and `languages.json` to make this change. I've pasted an example that's from the same function where it adds the `env` property, `shebang_paths` should be quite similar. If have any questions feel free to ask, and I will answer as best I can.

https://github.com/XAMPPRocky/tokei/blob/2c41fdb182b7ba1bcc7c9d1cfc0de569538e7f0d/src/language/language_type.hbs.rs#L477-L487

**Comment by solanav** [comment]
Thanks! I already made the change that it needed to work in my fork. Right now I'm checking this piece of code:
```rust
let extension = fsutils::get_extension(&entry);
        let filetype = extension.as_ref()
            .map(|s| &**s)
            .or_else(|| get_filetype_from_shebang(&entry));

if let Some(extension) = filetype {
...
``` 

Even though `get_filetype_from_shebang` should return the filetype, in is extracting an extension from the Some(). So when it tries to match the extension to the list of languages, it does not detect files identified by the shebang and returns None. Should I fix that in the same pull request?

**Comment by XAMPPRocky** [comment]
Hmm, yeah I don't like how that currently works, I always meant to refactor that. I think I would want that logic to look more like the code below. Adding two new `pub` methods `from_file_extension` and `from_shebang_path` that are both `fn(&str) -> Self`. If you'd also like to add this change, you can include it your PR since it's largely touching the same code anyway, I would make them as two seperate commits though.

```rust
fn from_path() -> Self {
    ...
    let extension = fsutils::get_extension(&entry);
    extension.as_ref()
             .map(|s| LanguageType::from_file_extension(&**s))
             .or_else(|| LanguageType::from_shebang_path(&entry))
}
```

**Comment by solanav** [comment]
Yeah that seems like a better idea, I'll get to it.
