### ISSUE TITLE
tokei ignores .pyw files

### ISSUE THREAD

**Issue by mark-summerfield** [XAMPPRocky/tokei#444]
`.pyw` is a legitimate suffix for Python files (e.g., for GUI applications on Windows); so with `-tPython` both `.py` _and_ `.pyw` files ought to be counted.

**Comment by XAMPPRocky** [comment]
@mark-summerfield Thank you for your issue! Can you provide some documentation about this extension? I'm happy to include it, if you'd like to make a PR yourself adding the change all you need to do is add it to [python's `extensions` in `languages.json`](https://github.com/XAMPPRocky/tokei/blob/master/languages.json#L1394-L1396)

**Comment by mark-summerfield** [comment]
Done; see https://github.com/XAMPPRocky/tokei/pull/445
