### ISSUE TITLE
Offtopic: What on earth was that release

### ISSUE THREAD

**Issue by ZanderBrown** [XAMPPRocky/tokei#448]
That email sure woke me up

**Comment by XAMPPRocky** [comment]
Sorry! I didn't realise people were watching the releases. 😅 I'm testing migrating all of tokei's CI requirements to GitHub Actions so there will be more weird test releases until it's ready.

**Comment by ErichDonGubler** [comment]
Hah, I've been getting a BUNCH of notifications and I was worried @XAMPPRocky had gotten hacked or something with the (relatively) large volume of releases with weird version numbers.

Good to know it's expected and just part of experimenting with some new infra. :)

**Comment by XAMPPRocky** [comment]
I'm closing this as the experiment is over and I now have the CI the way I want. If you'd like to use Tokei's CI I created the new CI configuration as a seperate template for projects. https://github.com/XAMPPRocky/mean-bean-ci-template
