### ISSUE TITLE
Extracting the "parsing" part of this into a separate library crate

### ISSUE THREAD

**Issue by HarrisonMc555** [XAMPPRocky/tokei#455]
Would you be interested in pulling out the "parsing" part of this crate into a separate library crate? I was recently considering creating a tool that would extract string values (e.g. `"Hello"` from `println!("Hello");`) from source files. Considering you already have code here that parses all kinds of source files and knows where the strings are, I could really take advantage of it if it were in a separate crate.

If that's not something you would consider doing at this time, though, I completely understand--it may require a lot of rearranging.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Tokei is already available as a library on crates.io ([Documentation](https://docs.rs/tokei/10.1.2/tokei/)), and you would be able to use it for that. I would recommend looking at the [`LanguageType`](https://docs.rs/tokei/10.1.2/tokei/enum.LanguageType.html#methods) enum which is an enum of every language in tokei, which has methods like `quotes` for getting the list of string delimiters.

**Comment by HarrisonMc555** [comment]
Ok sounds great, thank you very much!
