### ISSUE TITLE
~/.tokeirc ignored

### ISSUE THREAD

**Issue by danielzgtg** [XAMPPRocky/tokei#459]
The file `~/.tokeirc` is ignored when `tokei` is not run in `~`. tokei should use three sources of configuration: defaults < `~/.tokeirc` < `./.tokeirc`

The current behavior is not convenient for me. Most of my command line tools such as Bash and Vim conveniently read their config from `~`. I move around directories and run tokei. I also use tokei to calculate the number of lines of code in Git projects that I just cloned, and none them have `.tokeirc` in every directory.

The current workaround is to copy the `.tokeirc` to the current directory before running it. The problem with that is that I have to remove the file or be careful to not commit it to Git. If the project is mounted read-only, then I would need to go through copying the files to a temporary directory.

Example of the actual behavior (desired behavior would be tokei to output the same thing for both times I run it): 

```
home@daniel-tablet1:~$ mkdir test
home@daniel-tablet1:~$ cd test
home@daniel-tablet1:~/test$ cat > test.py << END
> """
> Test123
> """
> END
home@daniel-tablet1:~/test$ tokei
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Python                  1            3            3            0            0
-------------------------------------------------------------------------------
 Total                   1            3            3            0            0
-------------------------------------------------------------------------------
home@daniel-tablet1:~/test$ cp ~/.tokeirc .
home@daniel-tablet1:~/test$ cat .tokeirc 
treat_doc_strings_as_comments = true

home@daniel-tablet1:~/test$ tokei
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Python                  1            3            0            3            0
-------------------------------------------------------------------------------
 Total                   1            3            0            3            0
-------------------------------------------------------------------------------
home@daniel-tablet1:~/test$
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! By default tokei will look at your configuration directory (which is `$HOME` for some systems) or the current directory. I wouldn't have an issue also adding the home directory explicitly.

If anyone wants to adds this functionality it should be pretty easy to add, all that is needed is adding another file to `from_config_files`. I would expect the file precedence to be as follows.


1. Current directory
2. Home directory
3. Configuration directory
 https://github.com/XAMPPRocky/tokei/blob/a9667b95c0b5dbc6794b5e4fee8dedb4be2ac3e2/src/config.rs#L75-L97

**Comment by danielzgtg** [comment]
Oh, there is a config directory! I completely missed the fact that the `.tokeirc` goes in `~/.config/` not `~`.

Adding `~` to the precedence doesn't matter that much to me anymore, as I only needed something that's not the current directory to use as a global config.

Now I see the real issue is rather that this behavior should be documented. I looked through `README.md` and `.tokeirc.example` and I didn't find anything that said where to put it, so I wrongly assumed `~`.

**Comment by XAMPPRocky** [comment]
This has been fixed on master, and will be available in the next release
