### ISSUE TITLE
Fails to install on Ubtuntu 18.04

### ISSUE THREAD

**Issue by flanglet** [XAMPPRocky/tokei#468]
rustc --version
rustc 1.38.0-nightly (c798dffac 2019-07-27)

cargo install --path tokei
[...]

   Compiling toml v0.5.6
error[E0658]: use of unstable library feature 'map_get_key_value'
   --> /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.7.0/src/lib.rs:609:37
    |
609 |         if let Some((k, v)) = shard.get_key_value(key) {
    |                                     ^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49347
    = help: add `#![feature(map_get_key_value)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'map_get_key_value'
   --> /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.7.0/src/lib.rs:639:43
    |
639 |         if let Some((kptr, vptr)) = shard.get_key_value(key) {
    |                                           ^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49347
    = help: add `#![feature(map_get_key_value)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'map_get_key_value'
   --> /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.7.0/src/lib.rs:659:43
    |
659 |         if let Some((kptr, vptr)) = shard.get_key_value(key) {
    |                                           ^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49347
    = help: add `#![feature(map_get_key_value)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'map_get_key_value'
   --> /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.7.0/src/lib.rs:717:43
    |
717 |         if let Some((kptr, vptr)) = shard.get_key_value(&key) {
    |                                           ^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49347
    = help: add `#![feature(map_get_key_value)]` to the crate attributes to enable

   Compiling serde_json v1.0.48
error[E0658]: use of unstable library feature 'map_get_key_value'
   --> /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.7.0/src/mapref/entry.rs:106:37
    |
106 |             let (k, v) = self.shard.get_key_value(&c).unwrap();
    |                                     ^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49347
    = help: add `#![feature(map_get_key_value)]` to the crate attributes to enable

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `dashmap`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tokei v11.0.0 (/mnt/ddd4dfd5-591c-4868-b1f3-f2c8b0ab4ba6/ws/tokei)`, intermediate artifacts can be found at `/mnt/ddd4dfd5-591c-4868-b1f3-f2c8b0ab4ba6/ws/tokei/target`

**Comment by XAMPPRocky** [comment]
@flanglet Thank you for your issue! Tokei only supports the latest stable compiler, you need to update your rust version. You can do with `rustup update`, and then it should work.

**Comment by xmo-odoo** [comment]
@XAMPPRocky 18.04 has rustc 1.39 in apt so probably the source of the issue, it's possible to `apt install cargo` but then tokei fails to install.
