### ISSUE TITLE
Arduino support

### ISSUE THREAD

**Issue by rubdos** [XAMPPRocky/tokei#474]
I just noticed there's no Arduino support. I'm willing to contribute that, but there's a decision to make first.

Arduino code is basically glorified C++ code, with `int main() {}` replaced with `void loop() {}` and `void setup() {}`.  They list it in `.ino` files (hence the issue with Tokei), so the question would be whether to consider it a different language or include it under C++ as a language.

Stay safe!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I would just copy the C++ definition in `languages.json` and change what's different. You can read more about what's needed when adding a language in the [contributing.md](https://github.com/XAMPPRocky/tokei/blob/master/CONTRIBUTING.md).

https://github.com/XAMPPRocky/tokei/blob/5cf5bd235b9745ada7b7cbd5a058a39d99f83462/languages.json#L199-L205
