### ISSUE TITLE
Rustc .d dep-info files considered to be written in D

### ISSUE THREAD

**Issue by bjorn3** [XAMPPRocky/tokei#480]
Their syntax is actually Makefile like.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This is a [known limitation](https://github.com/XAMPPRocky/tokei#tokei-says-i-have-a-lot-of-d-code-but-i-know-there-is-no-d-code). You can either use the `-e/--exclude` flag or add a `.tokeignore` file to your repository to ignore the `.d` files. You can also follow #67 for being able to map an extension to a particular language.
