### ISSUE TITLE
parse_from_slice behavior with empty byte slice

### ISSUE THREAD

**Issue by NickHackman** [XAMPPRocky/tokei#515]
Using [parse_from_slice](https://docs.rs/tokei/11.1.0/tokei/enum.LanguageType.html#method.parse_from_slice) when iterating over a file line by line parsing a `""` results in a `Stat` of

```rust
Stats {
	comments: 0,
	blanks: 0,
	code: 0,
	lines: 0,
	path: "doesn't matter",
}
```

Is the intended result that this counts as nothing? Rather than a blank link?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! `LanguageType::parse_from_slice` isn't supposed to be used line by line, it requires the full text of the file. As there are heuristics that only work when tokei has multiple lines to work with.

**Comment by NickHackman** [comment]
That makes sense, line by line wouldn't handle multi-line comments or strings.

I'm walking the git blame of a file and trying to attribute lines based on the type. Line by line is a naive approach (using the full chunk is better), but for the most part gets what I'm going for. 

What would be the most accurate or least bad way to do this with Tokei? :smile:

**Comment by XAMPPRocky** [comment]
@NickHackman I would recommend not using Tokei for this part of your code, and instead build your own `parse` equivalent that using tokei's `LanguageType` API to get the information on the languages themselves.

```rust
trait LanguageTypeExt {
  pub fn parse_chunk(self, chunk: !) -> Stats
}
```

**Comment by NickHackman** [comment]
That makes sense! Can't believe I didn't think of that. 

Thank you, I really appreciate your help and your work on Tokei. :heart:

Closing
