### ISSUE TITLE
Publicize Tokei Internals

### ISSUE THREAD

**Issue by NickHackman** [XAMPPRocky/tokei#518]
Sorry, this sort of a continuation of #515. 

The best way in order to solve my problem, as we discussed in the previous issue would be to annotate the lines of a file in full, that way it handles possible contexts that `parse_from_slice` on a singular line would fail to. I realize that's out of the scope of Tokei. But...

Would it be possible to make `SyntaxCounter` and `SharedMatchers` used by Tokei public? So it would be possible to re-implement `parse_from_slice` for many different use cases? Specifically in my case, I'd be able to annotate files.

Thanks for all your work on Tokei

**Comment by NickHackman** [comment]
Closing, lack of interest

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I wouldn't infer that me not replying is a lack of interest, if I haven't replied is that I haven't found the time. That being said I don't see what the benefit of making them public, and I think my original advice was a bit off. You can just use `parse_from_slice` as long you know the syntax between the start and end is valid syntax.

**Comment by NickHackman** [comment]
I'm sorry! :heart: 

So the original usage of `parse_from_slice` you were right, it caused obscure and most of the time wrong results. Ideally for my solution I have a file annotated line by line with `Comment`, `Blank`, or `Code` and can then walk that with the blame provided by `git2`. That just isn't possible with Tokei as of right now, but with opening up how internals parse it wouldn't be too bad to rewrite `prase_from_slice` since this is a very minor change to the original `parse_from_slice`.

Any suggestions or discussion is appreciated :smiley:
