### ISSUE TITLE
Add option to exclude one or more languages from matching

### ISSUE THREAD

**Issue by passcod** [XAMPPRocky/tokei#528]
Here's the listing for one of the projects I work on:

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 ASP.NET                 1            1            1            0            0
 BASH                    8          216          159            8           49
 C#                      1           73           51           13            9
 CSS                   118        24427        21454          892         2081
 HTML                  121        11091         9727          105         1259
 INI                     1            4            4            0            0
 JavaScript            236        57035        40356         7704         8975
 JSON                   23        32418        32418            0            0
 Markdown                6         2312         2312            0            0
 Pan                   523        50205        38658          123        11424
 PHP                  1509       338217       195763        56690        85764
 Sass                   32         6172         4626          310         1236
 Shell                   3           17           11            3            3
 SVG                    38         3002         3000            0            2
 Plain Text             11         1001         1001            0            0
 Vue                     5         1094          925            0          169
 XML                     9          936          850           19           67
 YAML                    1         3313         3313            0            0
-------------------------------------------------------------------------------
 Total                2646       531534       354629        65867       111038
-------------------------------------------------------------------------------
```

That project contains no `Pan`. Nor does it `C#` or `ASP.NET`.

It would be nice if I could tell tokei that, and have it exclude them from its consideration when matching languages, to get more accurate results.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! While not exactly what you want, you can can exclude files based on file paths with `-e/—exclude` (or create a file called `.tokeignore`) or set a whitelist of languages with the `-t/—types` flag. You can also set `types` in your `.tokeirc` file, so that you don't have to set it each time.

Whether there should be a exclude based on languages is something I'll have to think about more.

**Comment by passcod** [comment]
Does the types option remove the results from the listing or does it force the whitelist earlier in the matching process? That's not clear from the help

In case that was ambiguous, I'm not looking to exclude whatever files match as Pan here: it's 50k lines after all and I'd love to know what they are, not just remove those lines from being listed altogether

**Comment by XAMPPRocky** [comment]
> Does the types option remove the results from the listing or does it force the whitelist earlier in the matching process? That's not clear from the help

If `types` is specified Tokei will only analyse files that matches any of the languages in `types`.

> In case that was ambiguous, I'm not looking to exclude whatever files match as Pan here: it's 50k lines after all and I'd love to know what they are, not just remove those lines from being listed altogether

@passcod You can see what files tokei has found with `tokei -f`.

**Comment by passcod** [comment]
Right, so this feature request is to remove Pan, as in the language from tokei's side, not the files from "my" side, which I know aren't Pan, from consideration to even be matched on. Ideally the files should classify as whatever next closest language match. Dunno how matching works here, maybe that's not possible.

**Comment by XAMPPRocky** [comment]
Well I'm not going to remove languages, you can always change the `languages.json` and build from source with `cargo install --path` yourself to match your needs.

**Comment by passcod** [comment]
No, I mean, to _add an option_ that removes _a language_. Not to remove a language permanently. Not to remove the lines that matched as that language. To omit, for that one run, the language(s) specified, from the matching.
