### ISSUE TITLE
Make it available on the Scoop package manager

### ISSUE THREAD

**Issue by jimleroyer** [XAMPPRocky/tokei#530]
I see no easy option to install tokei via a dedicated Windows package manager such as Scoop or Chocolatey. I'd be willing to cover the Scoop portion if you are good with this.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You're more than free to add support for scoop or chocolately, I wouldn't have the time or expertise to do so.

**Comment by vkrol** [comment]
It's avaiable on Scoop https://github.com/ScoopInstaller/Main/blob/master/bucket/tokei.json.

**Comment by XAMPPRocky** [comment]
Thank you for letting me know. I've added it to the README.
