### ISSUE TITLE
Badge endpoint

### ISSUE THREAD

**Issue by ofek** [XAMPPRocky/tokei#545]
Hello! Do we condone other projects using https://tokei.rs/b1/github/repo/user?category=code

If so, I'll begin now 🙂

**Comment by XAMPPRocky** [comment]
Hello, yes other projects are free to use it. I would appreciate supporting the project on [GitHub sponsors](https://github.com/sponsors/XAMPPRocky), as it pays for hosting and maintenance, but it is not required!
