### ISSUE TITLE
Specify the --sort option in the configuration file

### ISSUE THREAD

**Issue by Oxyriser** [XAMPPRocky/tokei#548]
It would be great if the configuration file was able to configure the default for the `--sort` cli option as it does for the `--type` option for example.

Hence, with a `.tokeirc` like this:
```toml
sort = "lines"
```
Calling `tokei` would be the same as calling `tokei --sort=lines`

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This should be pretty easy to add. It requires adding the `sort` parameter to `Config`, and adding the correct override behaviour to `Cli::override_config`. If someone would like to take this on I would be happy to mentor making the contribution and give feedback.
