### ISSUE TITLE
Exclude flag has no effect when running from absolute path

### ISSUE THREAD

**Issue by o2sh** [XAMPPRocky/tokei#564]
Hi,

When running tokei from an absolute path the `--exclude` flag doesn't seem to work.

![image](https://user-images.githubusercontent.com/13710835/85235197-82334d80-b413-11ea-95a2-a18244a3195e.png)
--> OK

![image](https://user-images.githubusercontent.com/13710835/85235187-6cbe2380-b413-11ea-913c-f79468f7f21a.png)
--> OK

![image](https://user-images.githubusercontent.com/13710835/85235233-b0189200-b413-11ea-9c9f-c593b254b018.png)
--> Not OK

**Comment by XAMPPRocky** [comment]
@o2sh Thank you for your issue! Tokei's `--exclude` works exactly like gitignore so I believe what is required is that tokei changes directories to the directory provided by the user. If someone is interested I would accept a PR that adds that. It should be a simple addition to `src/main.rs`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Excludes behave exactly the same as `gitignore`, so you're going to have to change your exclude pattern to be able to handle absolute paths.

**Comment by o2sh** [comment]
Thanks for your reply @XAMPPRocky, but I don't really see what you mean by 

> change your exclude pattern to be able to handle absolute paths.

I tried tokei `/home/o2sh/dev/onefetch -e /home/o2sh/dev/onefetch/src/main.rs` without success.

What's really weird is that it works at directory level but not at file level:

![image](https://user-images.githubusercontent.com/13710835/85947224-8d253b00-b949-11ea-8dac-a53f513e0fc5.png)

**Comment by XAMPPRocky** [comment]
@o2sh I mean that the behaviour is intentional. You can read more about how the gitignore pattern works here. https://git-scm.com/docs/gitignore#_pattern_format

**Comment by o2sh** [comment]
alright, so I guess the only way would be to `cd` to the directory before running tokei.

**Comment by XAMPPRocky** [comment]
No, it would work if you changed the pattern to `**/src/main.rs` as described in the link.
