### ISSUE TITLE
Markdown language detection with "rust,ignore" mdbook syntax?

### ISSUE THREAD

**Issue by repi** [XAMPPRocky/tokei#569]
Thanks for an awesome v12 release!

When we tried it out with the new embedded language support I noticed an oddity in our Markdown listing: most of our Rust example code in `.md` files wasn't showing up.

Turned out that our markdown blocks that used ` ```rust` as a prefix worked fine, but most of our Rust markdown code is not runnable Rust code so it uses ` ```rust,ignore` as language specifier which Tokei doesn't seem to support (yet).

We also use mdbook with our markdown files and mdbook supports more such code block specifiers such as ` ```rust,no_run,noplaypen` ([example](https://rust-lang.github.io/mdBook/format/mdbook.html)).

Verified that if we remove the `,ignore` or the `,no_run,noplaypen` parameters then tokei properly detects it as Rust code inside Markdown.

Possible to add support for this in the tokei markdown parsing?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes tokei currently doesn't handle this however should be a simple addition, I plan to release a patch later today which should include a fix for this.

**Comment by repi** [comment]
Awesome, thanks!

**Comment by XAMPPRocky** [comment]
This has been fixed and published as `12.0.4`.
