### ISSUE TITLE
Feature request: count test code

### ISSUE THREAD

**Issue by DougLau** [XAMPPRocky/tokei#578]
It would be very useful to separate test code from the normal line count, similar to how comments are treated.  I have some projects which are 50% test code by line count, and it would be nice to easily see this data.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However that would be significantly harder to parse as test code is only distinguishable if you understand the specific language in a way tokei currently can't. This would be more appropriate in a tool that is much more aware and specific to an individual language.

**Comment by walles** [comment]
Ref: <https://github.com/boyter/scc/issues/216>
