### ISSUE TITLE
Please add an ARM build into the CI suite.

### ISSUE THREAD

**Issue by Lokathor** [XAMPPRocky/tokei#582]
Because of https://github.com/tkaitchuck/aHash/issues/37, `tokei-12.0.4` cannot build on ARM.

What I'd like to request is that you expand the CI process of `tokei` so that there's an ARM build performed, so that this unfortunate accident can be avoided in the future.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However Tokei's CI already tests ARM targets (`aarch64-apple-ios`, `aarch64-unknown-linux-gnu`, `aarch64-unknown-linux-musl`). So this problem must be more specific than just ARM.

**Comment by Lokathor** [comment]
Ah, I found out what happened.

* `tokei` depends on `dashmap = { version = "3.11.4", features = ["serde"] }`
* [dashmap-3.11.4](https://crates.io/crates/dashmap/3.11.4) depends on `ahash ^0.3.5`
* [dashmap-3.11.5](https://crates.io/crates/dashmap/3.11.5) depends on `ahash ^0.4.0`

So it's not your fault at all here, the `dashmap` folks are in error this time.
