### ISSUE TITLE
--no-ignore should imply parent and vcs

### ISSUE THREAD

**Issue by Livven** [XAMPPRocky/tokei#585]
I think the current behavior is very confusing and unintuitive, as also evidenced by #452. Even if you do understand the behavior, having to specify all three flags is annoying. At least there should be an additional flag that turns off everything at once.

Looking at ripgrep, its `--no-ignore` implies `--no-ignore-dot`, `--no-ignore-exclude`, `--no-ignore-global`, `--no-ignore-parent`, `--no-ignore-vcs`, so I think tokei should follow that.

This would of course be a breaking change though. Not sure how you handle that, though I think this would be worth a breaking change :)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Changing this behaviour would be considered an acceptable breaking change to me. If someone would like to contribute this feature it is more than welcome.
