### ISSUE TITLE
WinGet-based installation

### ISSUE THREAD

**Issue by zkat** [XAMPPRocky/tokei#586]
It would be really great to be able to install tokei on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I’ve been trying to get Tokei available on winget however winget requires that you have an installer for Windows, AFAICT it does not allow installation of plain binaries like most packagers.

So the first thing that needs to be done unless winget changes is to implement a installer for Windows. I don’t currently have the time or a machine to implement and test a Windows installer. However if someone wants to work on this I would be happy to help  and give guidance where possible.

**Comment by XAMPPRocky** [comment]
Relevant issue: https://github.com/microsoft/winget-cli/issues/182

**Comment by cglong** [comment]
This is now done via microsoft/winget-pkgs#111759! 🎉

**Comment by XAMPPRocky** [comment]
@cglong Thank you for requesting it, and thank you @mdanish-kh for contributing it. 🙂
