### ISSUE TITLE
Feature: support HAML files

### ISSUE THREAD

**Issue by elalemanyo** [XAMPPRocky/tokei#587]
Hi,
Would be great if it also supports haml files.

Thanks for this great repo!
g/

**Comment by XAMPPRocky** [comment]
Thank you for your issue! While I don't have the time to add support myself, adding a language is easy, there's documentation on how to add a language in the [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md).

**Comment by NickHackman** [comment]
I'll add haml if that's okay with @elalemanyo

**Comment by XAMPPRocky** [comment]
Pasting from the PR

> I think for now I'm going to close this and the related issue as won't fix. As currently this the first language I've found with a comment syntax like this, and I don't think it would be worth the effort for just this case. If there are more found cases of indentation sensitive comments in languages, I think that can change however.
