### ISSUE TITLE
Duplicates in `tokei --help`'s possible output formats

### ISSUE THREAD

**Issue by TomerShech** [XAMPPRocky/tokei#589]
when I run `tokei --help` (or `tokei -h`) I get `json` printed twice. this must be a mistake, right?

Don't know if this info is helpful, but I'll supply it anyway: I'm on macOS Catalina, version 10.15.5. Using Fish as my shell, iTerm2 as my terminal emulator. Installed tokei from homebrew.

`tokei --version` outputs: `tokei 12.0.4 compiled with serialization support: json, cbor, yaml`.

<img width="992" alt="Screen Shot 2020-07-14 at 20 02 50" src="https://user-images.githubusercontent.com/36572700/87454931-591a6d00-c60d-11ea-949f-ee982ff7ffab.png">

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This has been fixed on master and will be available in the next release
