### ISSUE TITLE
HTML panic

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [XAMPPRocky/tokei#598]
1. In an empty directory, create `index.html` with the following content:
```html
<script></script>
```
2. Run `tokei`.

I get this:
```
thread '<unnamed>' panicked at 'index 1 out of range for slice of length 0', src\utils\ext.rs:51:10
```

Version info:
```
> tokei --version
tokei 12.0.0 compiled with serialization support: json, cbor, yaml
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You're using an old version of tokei. If you update to the latest version that should be fixed.
