### ISSUE TITLE
Incorrect sorting by lines of code

### ISSUE THREAD

**Issue by ItIsApachee** [XAMPPRocky/tokei#602]
When using `tokei -f -s code src/`, sorting works incorrectly for Rust files if some files contain Markdown, and others don't. In my case file with the biggest amount of lines of code appears to be in the end of the list, instead of the top.
![issue](https://user-images.githubusercontent.com/22821748/89357404-0d695980-d6c9-11ea-8f78-a980eb885656.png)

**Comment by XAMPPRocky** [comment]
For the sake of presentation all files that contain other languages are weighted to the bottom of the list. While it's not the most intuitive, it's a lot more readable in my opinion than the alternative of showing them interspersed with small entries.

**Comment by ItIsApachee** [comment]
> Thank you for your issue! For the sake of presentation all files that contain other languages are weighted to the bottom of the list. While it's not the most intuitive, it's a lot more readable in my opinion than the alternative of showing them interspersed with small entries.

Is there a way to just show total amount of lines of the file without mentioning another languages?

**Comment by XAMPPRocky** [comment]
Currently, no. If someone wants to add that as an option feel free.
