### ISSUE TITLE
Feature: --comact option for hiding another language inside of one.

### ISSUE THREAD

**Issue by ItIsApachee** [XAMPPRocky/tokei#605]
As discussed [here](https://github.com/XAMPPRocky/tokei/issues/602), at the moment there's no way to disable showing languages inside language, e.g. Markdown inside Rust, so it would be useful to have an option to disable nested languages, for showing sorted lines of code ignoring nested languages.

Also I'd like to implement this myself, if nobody minds.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Feel free to take this issue.
