### ISSUE TITLE
12.0.4 and master segfault on Windows, when built with optimizations.

### ISSUE THREAD

**Issue by clemenswasser** [XAMPPRocky/tokei#612]
I am installing and testing `master` and `12.0.4` using the current stable compiler ` 1.45.2`.
All tests are passing.
But running `tokei` results in `STATUS_ACCESS_VIOLATION` (segfault).
However the debug build seems to run fine (So it could be caused through optimizations?).
When debugging it (release mode + debug info), it seems that it is crashing inside of the `ignore` crate, in the `walk.rs` file, in the `visit` method, on line `1293`, where all the thread handles are joined. [[link]](https://github.com/BurntSushi/ripgrep/blob/master/crates/ignore/src/walk.rs#L1294)
This seems to be called by your `utils/fs.rs`, in the `get_all_files` method, on line `57`, where you build and run the parallel file walkers. [[link]](https://github.com/XAMPPRocky/tokei/blob/master/src/utils/fs.rs#L57)

This was an issue in the past: #543

**Comment by lnicola** [comment]
Some debugging steps I would try:

 - does happen every time
 - does it happen in any repository, or on a specific one?
 - does it still happen with `--no-ignore`
 - I don't think we can use the ASAN/MSAN on Windows, but maybe something like https://drmemory.org will catch something?

**Comment by clemenswasser** [comment]
When I disable thin-lto it works.

**Comment by clemenswasser** [comment]
However, fat-lto seems to run fine.

**Comment by XAMPPRocky** [comment]
@clemenswasser Can you clarify your above LTO statements? They're not really clear what's working or failing.

**Comment by clemenswasser** [comment]
No LTO: working
Thin LTO: not working (The current setting for release builds)
Fat LTO: working

**Comment by XAMPPRocky** [comment]
Great, thank you! I'll push a hotfix release using fat LTO on Windows to address this while thin LTO is broken and open a issue on rust about thin LTO.

**Comment by XAMPPRocky** [comment]
@clemenswasser Would be able to try this release and verify if it works? It should been compiled with fat LTO. https://github.com/XAMPPRocky/tokei/releases/tag/v12.0.4a

**Comment by clemenswasser** [comment]
This release works for me.
I have tested it on yours and LLVM's repo.

**Comment by XAMPPRocky** [comment]
Thank you for checking. The 1.46.0 is next week so I think we can leave the instructions as is, and redirect anyone to this issue in the mean time.
