### ISSUE TITLE
Fails with SIGABRT when run in Firefox 80.0 codebase

### ISSUE THREAD

**Issue by Finermeerkat137** [XAMPPRocky/tokei#614]
I tried running `tokei` in the lastest Firefox source archive, but it failed and gave this error:

`thread '<unnamed>' panicked at 'index 3 out of range for slice of length 2', src/utils/ext.rs:55:10`

Here's the backtrace:

```
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: start_thread
  24: __GI___clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: “env RUST_BACKTRACE=1 tokei” terminated by signal SIGABRT (Abort)
```

This might just be an OOM error, but I'm not 100 percent sure, so I'll try again on a system with more memory.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Can you first ensure that you are running the latest version of tokei? I believe that should work.

**Comment by Finermeerkat137** [comment]
Sorry I was late, it does seem to work with the latest version and the version shipped by my distro was out of date.

**Comment by XAMPPRocky** [comment]
Thank you for letting me know, I'll close this for now then.
