### ISSUE TITLE
More code lines than expected for R package

### ISSUE THREAD

**Issue by ShixiangWang** [XAMPPRocky/tokei#618]
Dear developer,

I found the code counting is not consistent with codecov. For my R package https://github.com/ShixiangWang/sigminer, it reports ~30k.

[![Lines Of
Code](https://tokei.rs/b1/github/ShixiangWang/sigminer?category=code)](https://github.com/ShixiangWang/sigminer)

While actually ~6k code under my `R` directory. https://codecov.io/github/ShixiangWang/sigminer?branch=master. Even adding the codes in `tests`, the total number I think is around 10k.

![image](https://user-images.githubusercontent.com/25057508/91821354-0f432000-ec69-11ea-85ba-7857793c3ddd.png)

Best,

Shixiang

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Could run `tokei` on the the codebase and include the output? tokei.rs uses the total that tokei gives when cloning and running it on the repository.
