### ISSUE TITLE
The servier is down

### ISSUE THREAD

**Issue by HaojunRen** [XAMPPRocky/tokei#622]
Please fix it ASAP, thanks

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've restarted the server, so it should be up shortly. Unfortunately I can only maintain it with my spare time, if you'd like to help contribute to improving the uptime of https://tokei.rs you can sponsor the project through [GitHub Sponsors](https://github.com/sponsors/XAMPPRocky).
