### ISSUE TITLE
The servier is down again

### ISSUE THREAD

**Issue by HaojunRen** [XAMPPRocky/tokei#632]
Please fix this issue, thanks a lot

**Comment by MonliH** [comment]
Yep, the server's down. May partially be [my fault](https://github.com/badges/shields/pull/5547); probably a lot of fo people started using it.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! it's back up.

**Comment by HaojunRen** [comment]
Yeah, perfectly

**Comment by MonliH** [comment]
Awesome, that's good to hear!
