### ISSUE TITLE
Add support for .pug files

### ISSUE THREAD

**Issue by spenserblack** [XAMPPRocky/tokei#671]
[Pug.js](https://pugjs.org/) is a template engine language that renders HTML. A pug template can be written in `.pug` files.

***

I would happily make a PR myself, but I'm unsure of what to put for the `"quotes"` key. The issue is that quotes (e.g. `"`) are sometimes quotes for strings and sometimes literal quotes.

## Example

```pug
// example.pug
doctype html
html
  head
  body
    h1 "Hello, #{ "World" }!"
```
Becomes (indentation added for readability)
```html
<!doctype html>
<html>
  <head></head>
  <body>
    <h1>"Hello, World!"</h1>
  </body>
</html>
```

***

As you can see, the `"` outside of `#{ }` is a literal quote, while the `"` inside `#{ }` are quotes around a string. Per my understanding, this is the exact opposite behavior of the `"verbatim_quotes"` -- `"` is a verbatim quote *unless* it's wrapped by `#{ }`.

There can be any number of spaces inside `#{ }`, so I don't know if `"quotes"` can just be set to `[["#{\\\"", "\\\"}"], etc.]`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Quotes is not white space sensitive, so including `#{}` should be fine. That is a tricky case, but I think I would be fine if there's a bit of inaccuracy here because there isn't much we could do to figure it out except have a pug specific parser in the code.

**Comment by spenserblack** [comment]
Thanks! I'll go with that for now.

Another issue I'm unsure about is Pug's block comments. Instead of having tokens that end the comment, like `*/`, the block comments are indentation sensitive. For example:

```pug
//-
  This
  is a block comment.
p This is not.
```
Is this style of comment supported by tokei currently? If not, should I simply exclude the `multi_line_comments` key for now?

**Comment by XAMPPRocky** [comment]
Yeah, they're isn't any handling of indentation, so excluding it seems fine. I don't think there has been another case of indentation sensitive multi-line comments, if there are more languages that have that we could add support for it.
