### ISSUE TITLE
Total of files displayed as zero

### ISSUE THREAD

**Issue by Byron** [XAMPPRocky/tokei#684]
Starting from 34810da843ebb21fb984de0bd8832a3bfd625315 (as found via `git bisect`) `tokei` doesn't seem to compute the total amount of files counted anymore.

Personally I found this informative so I wonder if there was a reason to remove the count and I am missing something, or if this could be a regression.

Thanks a lot.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That's not intentional, just an unfortunate side effect of the change. I'll publish a fix later today.
