### ISSUE TITLE
tokei now available on NetBSD

### ISSUE THREAD

**Issue by voidpin** [XAMPPRocky/tokei#689]
FYI, https://mail-index.netbsd.org/pkgsrc-changes/2021/01/01/msg225999.html

**Comment by XAMPPRocky** [comment]
Thank you for letting me know! Do you also want to add the command to install it to the README?

**Comment by voidpin** [comment]
If you'd like that, it would be nice :)

Using the package manager:
`# pkgin install tokei`

Building from source:
```
$ cd /usr/pkgsrc/devel/tokei
# make install
```

**Comment by XAMPPRocky** [comment]
I’ve now included it in the README.
