### ISSUE TITLE
Lazarus (Free Pascal) project CudaText, missed .inc files

### ISSUE THREAD

**Issue by Alexey-T** [XAMPPRocky/tokei#708]
project
https://github.com/Alexey-T/CudaText

folder app/

```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 ASP                     4           40           24            0           16
 C                       2           28            6           16            6
 C++                     2           14           12            0            2
 CSS                     4         2516         2510            6            0
 INI                    14         6590         6140          114          336
 JavaScript              2            6            4            2            0
 JSON                   36         5224         4660            0          564
 Pascal                 44        34984        29276         1535         4173
 PHP                     4           38           24            0           14
 Python                337       167943       150846         7215         9882
 SVG                    24           24           24            0            0
 Plain Text             87         7386            0         6430          956
 VBScript                2            8            4            4            0
 XSL                     2           16           10            0            6
 XML                     2            4            2            0            2
-------------------------------------------------------------------------------
 HTML                   12         1240         1072           56          112
 |- JavaScript           2            6            4            2            0
 (Total)                           1246         1076           58          112
===============================================================================
 Total                 578       226061       194614        15378        16069
===============================================================================
```
tool says- 44 pascal files

OK- folder app/ has 44 files .pas .lpr .lpi
bad- folder has ALSO 18 PASCAL FILES *.inc which are include files-- missed!

.inc files are NOT always pascal files. they are if they are in Lazarus or Delphi projects.

**Comment by Alexey-T** [comment]
NOTE2: to find .inc files, find the lines
```
    {$I filename.inc}
    {$I dir1/dir2/filename.inc}
    {$I ../dir3/fname.inc}
```
in pascal files. one .inc file can include another .inc file.
these `{$I}` lines can be in lowercasee `{$i}`.
they can be inside pascal code:
```
some_func(2); {$i ../fname.inc}; some_more;
```

**Comment by Alexey-T** [comment]
@Artem3213212 @dinkumoil @akizuha Support pls

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However as you've mentioned `.inc` isn't always pascal, and indeed many other languages have conventions of using `.inc`, and tokei does not use the contents of the file to detect the language, I'd rather not count it, than miscount a language as another. A potential future solution will be #67 which will allow to set `.inc` to be counted as whatever language you prefer, but in the meantime you can always give those files double extensions (e.g. `.inc.pas`) and tokei will count them correctly.

**Comment by Alexey-T** [comment]
>Tokei does not use the contents of the file to detect the language

It's a misfeature

**Comment by XAMPPRocky** [comment]
That’s your opinion, however I am unconvinced, I prefer the deterministic nature of the current implementation. You can always use another code counter such as [cloc or others](https://github.com/AlDanial/cloc#other-counters-), that use a different detection algorithm.
