### ISSUE TITLE
tokei.rs: Badge Always Returns Processing

### ISSUE THREAD

**Issue by HaojunRen** [XAMPPRocky/tokei#792]
It seems to display failed while lines more than 10000?
![图片](https://user-images.githubusercontent.com/42354711/122417335-fb7c6680-cfbb-11eb-8911-8df5864d4524.png)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However I can’t debug it without a link to the repository.

**Comment by HaojunRen** [comment]
1~2 days ago it works fine.

Try the link
https://tokei.rs/b1/github/Nepxion/Discovery?category=lines

Thanks

**Comment by HaojunRen** [comment]
![图片](https://user-images.githubusercontent.com/42354711/122438557-68e4c300-cfcd-11eb-8fc8-be60009696a1.png)

Refer to picture, it looks lines < 20000 dislay fine

**Comment by ljedrz** [comment]
Nope, lower number of lines fails to display too; below are the broken badges in my repo:
[![files](https://tokei.rs/b1/github/ljedrz/pea2pea?category=files)](https://github.com/ljedrz/pea2pea/tree/master/src)
[![LOC](https://tokei.rs/b1/github/ljedrz/pea2pea?category=code)](https://github.com/ljedrz/pea2pea/tree/master/src)

**Comment by HaojunRen** [comment]
Any solutions?

**Comment by XAMPPRocky** [comment]
I'm planning a solution, but I can only work on tokei and tokei.rs in my spare time, which at the moment is pretty thin. I had longer term plans to improve tokei.rs that will have to happen quicker to address this issue, but it's still going to take some time for that solution to be generally available. I hope to at least improve the situation by the end of the weekend, but it may slip.

**Comment by HaojunRen** [comment]
Thanks for response. Is it a bug or performance issue?

**Comment by h4sohail** [comment]
Having the same issue with our repo, was working fine but is stuck on processing now:
https://tokei.rs/b1/gitlab/carletonblueprint/beneficent?category=code

**Comment by XAMPPRocky** [comment]
Fix the underlying issue, which was systemctl filling up tmpfs to the point where it couldn't clone repositories.

**Comment by HaojunRen** [comment]
Hope it will be fixed ASAP, thanks very much

**Comment by XAMPPRocky** [comment]
It's already fixed?

**Comment by ljedrz** [comment]
Now the badge doesn't display for me, even though the SVG in the link seems fine :thinking:.

**Comment by HaojunRen** [comment]
I mean you can help us to fix it, not me. I can't understand solution you told. Is it related with github, that means github forbid you to calculate lines of repository?

**Comment by XAMPPRocky** [comment]
> I mean you can help us to fix it, not me. I can't understand solution you told. Is it related with github, that means github forbid you to calculate lines of repository?

You're misunderstanding what I'm saying. I said that I already fixed the issue.

> Now the badge doesn't display for me at all, even though the SVG in the link seems fine 🤔.

This is indeed odd, I've run into issues with camo (github's cache) before, I'll send a support request.

**Comment by HaojunRen** [comment]
> 
> 
> Now the badge doesn't display for me at all, even though the SVG in the link seems fine 🤔.

What is the svg code for tokei?

**Comment by ljedrz** [comment]
You can check out the links I posted [here](https://github.com/XAMPPRocky/tokei/issues/792#issuecomment-863867510) - they resolve to an SVG with the correct badge, it just doesn't display properly.

**Comment by HaojunRen** [comment]
I understand, click to download badge to local, it will show correctly

**Comment by XAMPPRocky** [comment]
Fixed, was an issue with the MIME type.

**Comment by HaojunRen** [comment]
yeah, perfectly, thanks

**Comment by ljedrz** [comment]
Everything works now, thanks :ok_hand:.
