### ISSUE TITLE
non-json response for lines of code

### ISSUE THREAD

**Issue by Hongbo-Miao** [XAMPPRocky/tokei#794]
I am having an issue using Shields badge. I originally created at https://github.com/badges/shields/issues/6637 @chris48s located the issue. Copy his answer below

> Hello. This is happening because https://tokei.rs/b1/github/Hongbo-Miao/hongbomiao.com it is returning a non-JSON response
> 
> ```
> curl -H "Accept: application/json" "https://tokei.rs/b1/github/Hongbo-Miao/hongbomiao.com"
> ```
> 
> If I call another URL like
> 
> ```
> curl -H "Accept: application/json" "https://tokei.rs/b1/github/badges/shields"
> ```
> 
> that returns JSON as expected. This appears to be an issue with the tokei.rs service so can you raise an issue with them please.

Thanks!

**Comment by calebcartwright** [comment]
fwiw I believe this is a duplicate of #792 and #788, or at least that they are all effects of the same underlying problem

**Comment by Hongbo-Miao** [comment]
Yup, I think so. Close as duplicate. Thanks!
