### ISSUE TITLE
For Golang, is go.mod and go.sum caluclated?

### ISSUE THREAD

**Issue by ntt720** [XAMPPRocky/tokei#795]
any hints?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! As you can see here, they are not currently. I would accept a PR adding them though.

https://github.com/XAMPPRocky/tokei/blob/abacbc525b5496336db828d1bdb650a68b29db65/languages.json#L489-L494

**Comment by lespea** [comment]
I personally think it'd be better for those not to be included, as they aren't really "source" files.  Just my $.02

**Comment by XAMPPRocky** [comment]
Alright. well I'll close this for now.
