### ISSUE TITLE
The badging service is down

### ISSUE THREAD

**Issue by ice1000** [XAMPPRocky/tokei#804]
![image](https://user-images.githubusercontent.com/16398479/126931761-d95da55b-14b3-4c4d-9e68-944188673c82.png)

**Comment by GopherJ** [comment]
yes the same to me

**Comment by GopherJ** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/33961674/126963324-8852cd15-cef7-4163-88e8-9f7a4e1d30d7.png">

**Comment by KartoshkaPy** [comment]
Now it's works (at least for me)
![image](https://user-images.githubusercontent.com/59607313/126966427-7c63503b-5d06-4fcb-a8d6-de4aa8f70c77.png)

**Comment by ice1000** [comment]
Wfm as well, closing
