### ISSUE TITLE
Parts of the output are showing in white color on white background when running in WSL2 in Alacritty

### ISSUE THREAD

**Issue by JKKross** [XAMPPRocky/tokei#805]
Hi,

I recently switched to light mode & noticed that some parts of the output are white text on white background.
Everything works correctly in Alacritty when using Windows PowerShell - this only occurs when I switch to WSL2.
I checked my colors in alacritty config & everything is set correctly (meaning only "background" & "white" is set to #FFFFFF)

Here is how it looks:
![example_a](https://user-images.githubusercontent.com/31014306/127006519-c35e7d81-f516-412a-830a-0db7083f9bb7.jpg)
Here with mouse-selected text:
![example_b](https://user-images.githubusercontent.com/31014306/127006525-51291022-519b-482f-96aa-355d4ebd4e17.jpg)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! It should be as simple as changing the colour for that text, if anyone wants to a PR is more than welcome.
