### ISSUE TITLE
Add a `--tracked` flag (or something similar)

### ISSUE THREAD

**Issue by spenserblack** [XAMPPRocky/tokei#828]
When I run `tokei` in a git repository, usually I want to know the stats of the *tracked* files. Sometimes I will add a file like `notes.txt` for myself, which I don't put in the `.gitignore` or any other ignore file since it's just temporary. This temporary file then gets included in the stats.
I think it would be helpful if we could specify that we only want the stats of files that are tracked. To avoid breaking changes, this should probably default to false, and be opt-in via a new CLI flag.

At bare minimum I think it should ignore untracked files, but it would be cool if it could also ignore untracked changes in tracked files, too.

The current workaround would obviously be to put untracked files in an ignore file like `.tokeignore` or `.gitignore`.

**Comment by alexmaco** [comment]
Currently, tokei uses [the ignore crate](https://docs.rs/ignore/) to walk and enumerate files. Ignore doesn't seem to support walking only the files that are tracked by git.

This means in order to obtain the list of files at the beginning by running `git ls-tree ...` (or equivalent for other SCMs), and then reading the files in that list, which implies supporting (and testing) with at least several other SCMs.

Interestingly, getting the file list locally from the rust and the firefox repos seems to be quite fast, about 3-6 seconds, which is 50-60% the runtime of tokei (with warm fs caches).

**Comment by spenserblack** [comment]
> This means in order to obtain the list of files at the beginning by running `git ls-tree ...` (or equivalent for other SCMs), and then reading the files in that list, which implies supporting (and testing) with at least several other SCMs.

The reverse can be done by getting the output of `git ls-files --others`, which would output untracked files and *ignoring* them, but otherwise running normally.

Now that I'm thinking about it, this request is probably overkill. Alternatively, if `--exclude` could accept multiple lines for multiple patterns, then `tokei --exclude "$(git ls-files --others)"` could be used (and could be made an alias for `tokei`).

**Comment by spenserblack** [comment]
Looks like `git ls-files | xargs tokei` is enough to meet my needs, actually. So, unless the maintainers consider `--tracked` to be a useful enough feature to implement, this issue can probably be closed.

**Comment by adamency** [comment]
`git ls-files | xargs tokei` doesn't work, just as `git ls-files | parallel tokei` doesn't work, and even `git ls-files -z | xargs -0 tokei` `git ls-files -z | parallel -0 tokei`, as they are spawning multiple independents `tokei` processes instead of just giving the full file list to `tokei`. Just take the [go](https://github.com/golang/go) repository for instance and you'll see what I'm talking about.

However, 

```
tokei $(git ls-files)
```
 works **in Bash**, but it's not portable. For instance it doesn't work in Powershell.

#### Conclusion

@alexmaco

`tokei` should **really** be able to read from a file list as an input file, e.g. like so:

```tokei --file-list <file_path>
```
or more adequately be able to take in the list from stdin, e.g. like so:

```
git ls-files | token -
```
or even better
```
git ls-files -z | token -0 -
```

to account for special characters and complex UTF-8 characters. `--tracked` of course would be a more comfortable option but only for that specific usecase.

**Comment by spenserblack** [comment]
> `--tracked` of course would be a more comfortable option but only for that specific usecase, while the proposed solution is extremely flexible, standard and generic.

Yeah, after coming back to this issue, it does feel a bit too narrow, and the effort might not be worth the output. Plus the Ruby gem github-linguist does something like this issue's request, so there's already an alternative for this use case.

An argument like `--file-list`, or maybe `--file-pattern`, would be good, and I'd be happy to change the issue title if the maintainer wishes.

>or more adequately be able to take in the list from stdin

My initial instinct is that stdin should be used for file *contents,* not names, but I'm not sure how useful that would be since tokei needs file extensions or shebangs AFAIK :laughing:

> `git ls-files | xargs tokei` doesn't work

I'm a bit confused by this, I'll admit. Works on my machine :laughing:

**Comment by adamency** [comment]
> My initial instinct is that stdin should be used for file contents, not names,

stdin should be used to provide the needed input to an executable. Period. What needs to be in stdin only depends on what input your program needs. E.g. `xargs` precisely takes a list of files as stdin. `rg` also accepts a list of files as stdin, etc... `tokei` is in the same category as far as *stdin* matters.

> I'm a bit confused by this, I'll admit. Works on my machine

Have you tried with the go repository I linked and specifically mentioned as a non-working example ?

**Comment by spenserblack** [comment]
>Have you tried with the go repository I linked and specifically mentioned as a reproducible non-working example?

Ah, I see what you mean now. I skimmed over the man page of `xargs` and didn't know about the max arguments, sorry :disappointed:

>stdin should be used to provide the needed input to an executable, period

Maybe I wasn't clear. I have a habit of bringing up devil's advocate arguments and then arguing against my own idea. I was saying that usage like `tokei < README.md` is basically impossible to implement since, as far as I know, tokei doesn't have and never will have heuristics, classifiers, or anything else that would be necessary to detect a language from a stream. Just detecting a language using extensions and shebangs alone is insufficient for such usage. Extensions can't be used for classifying a stream of text for obvious reasons, and shebangs would only work for a small set of languages. But if tokei *did* have more advanced classification methods, I would have been interested in being able to use stdin to classify and get stats of a stream of code. `curl https://example.com/path/to/source/code.ext | tokei` could have been interesting, for example. I was basically bringing up wishful thinking and saying why it can't be done.

Additionally, I think I misinterpreted what you meant by `--file-list`, but I think I understand now. To clarify, you were suggesting something like this, correct?
```bash
git ls-files -z > foo
tokei --file-list foo
```

**Comment by spenserblack** [comment]
Thinking on this a bit more, if `--file-list` is the chosen implementation, I think that this needs to be considered:

`--file-list` would effectively point to an "allow list" -- it would tell tokei to ignore all files except those in the file.

Tokei already supports a `.tokeignore`, but it doesn't look like the path to the ignore file can be overridden via the CLI. For the sake of keeping things "symmetrical", it might be worth considering implementing an `--ignore-list` option to go with the `--file-list` option. Though this raises the question of what should happen if both options are used :thinking:

Personally, I'd like the "file list" to support glob patterns. Basically a reverse `.gitignore`/`.tokeignore`. If it does accept globs, I wonder if there's a better word than "list" to describe its usage.

******

Side note: speaking about ignore files made me realize that the below is possible.

```bash
echo '*' > .tokeignore
git ls-files | awk '{print "!"$0}' >> .tokeignore
tokei
```
(or it should be, but it doesn't seem to work as expected in large repos like https://github.com/golang/go/commit/2baf8ad8311a9eb2c7d0352f32c46fb0e8b4afbe)
