### ISSUE TITLE
[Feature request] Process files not in the file system

### ISSUE THREAD

**Issue by bspot** [XAMPPRocky/tokei#842]
Hello!

Maybe this is already possible and I just couldn't find it:

When using tokei as a library, it would be nice if I could directly provide the file names and their content instead of file and directory names.

My use case is building a tool that generates a report of code size in a Git repository over time, i.e. for all the commits in the repository. I can extract all the files and their content from the repository, but since they don't live in the file system, I can currently not generate statistics for them using tokei.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This functionality is already available in tokei. All that is required is using one of the `from_*` (E.g. https://docs.rs/tokei/12.1.2/tokei/enum.LanguageType.html#method.from_file_extension ) methods, followed by using either `parse_from_str`/`parse_from_slice`.

**Comment by bspot** [comment]
Ah! Thank you very much,
