### ISSUE TITLE
Feature request: count lines of tests code

### ISSUE THREAD

**Issue by gww-certik** [XAMPPRocky/tokei#852]
Feature request: ability to count (maybe via optional flag `--count-tests`) lines of code that belong to tests.

**Comment by glazari** [comment]
A hard part about this is that each language has its own standards on how to treat test code. For example Java and python usually use separate directories for tests, Go uses separate files but in the same directory and Rust keeps unit tests in the same file as code they are testing.

Also what counts as test code? Are they only the code that is explicitly in a unit-test function? Or do helper functions only used for tests also count? In the case where test are in a separate file we could count the full file. But when they are mixed we need another way.

Having said that, I do think its useful to count tests. If anyone knows of some crate that solves the problem of identifying tests in many languages, I might take on the challenge to integrate it here

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yeah, as @glazari says this is something that requires more in-depth analysis of source code than tokei is currently capable of. If there are consistent conventions in langauges then maybe tokei could support something like this, but I'm not sure how possible that is.

**Comment by gww-certik** [comment]
Hello!

Heuristic that I am using in my scripts is following , usually tests are placed at the end of file and surrounded by:

```
#[cfg(test)]
mod tests {
(...)
}
```

(as you can see here: https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html )

It's not bullet proof, but does the job 97% of time.

(otherwise integration tests are in `tests/` https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html )

Maybe that's heuristic that could be worth considering for tokei.

**Comment by XAMPPRocky** [comment]
Yeah, that would work for Rust, but there would need to be enough other languages with similar heuristics to warrant the feature.
