### ISSUE TITLE
Showing zero in all repos

### ISSUE THREAD

**Issue by AbdulMalikDev** [XAMPPRocky/tokei#902]
This is for all repos using this badge.
![image](https://user-images.githubusercontent.com/47276307/161416893-dc14fb73-4122-45aa-960c-e1060ba32383.png)

**Comment by KekOnTheWorld** [comment]
Same issue here

**Comment by igorskyflyer** [comment]
+1, everything was working fine for me until the last 2-3 days 🥺

**Comment by KekOnTheWorld** [comment]
Issue is resolved for me

**Comment by AbdulMalikDev** [comment]
Issue resolved for me.

**Comment by Equim-chan** [comment]
It is happening again. Re-open the issue?
