### ISSUE TITLE
Sorting files within a language by line count?

### ISSUE THREAD

**Issue by nyanpasu64** [XAMPPRocky/tokei#926]
Is it possible to sort files in `-f/--files` display by their line count? This is useful for finding the largest files, and/or finding and excluding large vendored libraries with huge tables of data not interacted with by developers.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'm pretty sure this already implemented by adding `-s/--sort lines` to your command

**Comment by nyanpasu64** [comment]
I already tried that earlier. I could've sworn that the files within each section were not sorted in descending line count. But now that I look again, it *does* seem that the leftmost `Lines` column decreases, though the Code/Comments/Blanks columns to the right do not decrease monotonically.
