### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by QuarticCat** [XAMPPRocky/tokei#951]
See https://github.com/XAMPPRocky/tokei/blob/master/src/language/syntax.rs#L575-L581

```rust
if !self.quote_is_verbatim && window.starts_with(br"\\") {
	// ...
} else if !self.quote_is_verbatim && window.starts_with(br"\\") && ... {
    // ...
}
```

We can never reach this branch.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Your sample of that code is slightly off, it's not super clear what's happening there, but the first branch checks for `br"\\"`, and the second branch checks for `br"\"`. So these are two different cases, the first which is a special case for `\\` to treat it as a escaped `\` and skip over it, the second is checking if the next character is an escaped string literal. E.g. `\"`.

**Comment by QuarticCat** [comment]
Oh, I see. Sorry for bothering you.

**Comment by XAMPPRocky** [comment]
It's no bother at all. 🙂
