### ISSUE TITLE
Current now, tokei show svg [lines of code] is zero

### ISSUE THREAD

**Issue by baoyachi** [XAMPPRocky/tokei#959]
https://tokei.rs/b1/github/XAMPPRocky/tokei?category=code
<img width="585" alt="image" src="https://user-images.githubusercontent.com/10433001/205600972-ca123830-1bee-45ff-b06b-31325e7ee118.png">

**Comment by TheMostDiligent** [comment]
It still shows 0 lines of code as of this moment

![image](https://user-images.githubusercontent.com/61806567/211175988-b56a48be-9c80-4df3-a9ee-b969b24bd7ff.png)

**Comment by ChristopherRabotin** [comment]
This isssue has reappeared.
