### ISSUE TITLE
Lines of code not working!

### ISSUE THREAD

**Issue by sbkv1** [XAMPPRocky/tokei#968]
![image](https://user-images.githubusercontent.com/93185814/212480082-d1357eff-e05e-4a9b-a82d-d2a789bf0980.png)

```![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=code)```

![Lines Of Code](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=code)

**Comment by arch-user-france1** [comment]
seems working

**Comment by hackerceo** [comment]
Confirmed Jan 28th, 2023 that it is not working.  It shows 0 lines of code.

**Comment by arch-user-france1** [comment]
> Confirmed Jan 28th, 2023 that it is not working. It shows 0 lines of code.

just before I saw something with about 2k lines of code, if I remember correctly. But now it's 0.

**Comment by JordanWelsman** [comment]
Any response on this?

**Comment by XAMPPRocky** [comment]
https://github.com/XAMPPRocky/tokei_rs/issues/123#issuecomment-1209417268
