### ISSUE TITLE
Recursively count inside directories

### ISSUE THREAD

**Issue by kaushalyap** [XAMPPRocky/tokei#970]
According to my brief usage it seems that `tokei` only count source files directly in specified directory, but not recursively,
any option to count code recursively inside directories would be highly appreciated.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! But tokei does recursively count directories, are you sure it's not?

**Comment by kaushalyap** [comment]
Sorry my bad, I was trying it on front-end project and so way fewer lines for Typescript,  then I noticed there is separate row for `TSX`
